# This action defines when a pull request becomes ready for auto-rebasing
# This is normally done post-review, but we're doing it on pull request creation
name: Autosquash Label

on:
  pull_request:
    types: opened

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        labels: autosquash
